theme: jekyll-theme-slate
title: "House MD Hyperfixation"
description: "A silly little website about a 2004 TV show"
nav:
  - title: "Home"
    url: /
  - title: "About House MD"
    url: /About/AboutHouseMD.md
  - title: "Silly Memes"
    url: /Memes/SillyMemes.md
  - title: "My Headcanons"
    url: /Headcanons/MyHeadcanons.md
  - title: "Fanfictions"
    url: /Fanfictions/FanfictionRecommendation.md

include:
  - assets
  - _includes
